/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 character.glb 
*/

import React from "react"
import { useGraph } from "@react-three/fiber"
import { useAnimations, useGLTF } from "@react-three/drei"
import { SkeletonUtils } from "three-stdlib"

export function Character2(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF("/character.glb")
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={50}>
            <primitive object={nodes.Root} />
          </group>
          <group name="MushroomKing" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="MushroomKing_1"
              geometry={nodes.MushroomKing_1.geometry}
              material={materials.MushroomKing_Main}
              skeleton={nodes.MushroomKing_1.skeleton}
            />
            <skinnedMesh
              name="MushroomKing_2"
              geometry={nodes.MushroomKing_2.geometry}
              material={materials.Orc_Main}
              skeleton={nodes.MushroomKing_2.skeleton}
            />
            <skinnedMesh
              name="MushroomKing_3"
              geometry={nodes.MushroomKing_3.geometry}
              material={materials.MushroomKing_Secondary}
              skeleton={nodes.MushroomKing_3.skeleton}
            />
            <skinnedMesh
              name="MushroomKing_4"
              geometry={nodes.MushroomKing_4.geometry}
              material={materials.Eye_White}
              skeleton={nodes.MushroomKing_4.skeleton}
            />
            <skinnedMesh
              name="MushroomKing_5"
              geometry={nodes.MushroomKing_5.geometry}
              material={materials.Eye_Black}
              skeleton={nodes.MushroomKing_5.skeleton}
            />
          </group>
          <group
            name="Mushroom"
            position={[1.93, 1.76, -0.227]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <skinnedMesh
              name="Mushroom_1"
              geometry={nodes.Mushroom_1.geometry}
              material={materials.MushroomKing_Main}
              skeleton={nodes.Mushroom_1.skeleton}
            />
            <skinnedMesh
              name="Mushroom_2"
              geometry={nodes.Mushroom_2.geometry}
              material={materials.MushroomKing_Secondary}
              skeleton={nodes.Mushroom_2.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/character.glb")
