/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as NewGameRouteImport } from './newGame'
import { Route as IndexRouteImport } from './index'
import { Route as MockIndexRouteImport } from './mock/index'
import { Route as SaveGameSaveGameIdRouteImport } from './saveGame.$saveGameId'
import { Route as MockMockNameRouteImport } from './mock/$mockName'
import { Route as GameGameIriRouteImport } from './game.$gameIri'

const NewGameRoute = NewGameRouteImport.update({
  id: '/newGame',
  path: '/newGame',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockIndexRoute = MockIndexRouteImport.update({
  id: '/mock/',
  path: '/mock/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaveGameSaveGameIdRoute = SaveGameSaveGameIdRouteImport.update({
  id: '/saveGame/$saveGameId',
  path: '/saveGame/$saveGameId',
  getParentRoute: () => rootRouteImport,
} as any)
const MockMockNameRoute = MockMockNameRouteImport.update({
  id: '/mock/$mockName',
  path: '/mock/$mockName',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIriRoute = GameGameIriRouteImport.update({
  id: '/game/$gameIri',
  path: '/game/$gameIri',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/newGame': typeof NewGameRoute
  '/game/$gameIri': typeof GameGameIriRoute
  '/mock/$mockName': typeof MockMockNameRoute
  '/saveGame/$saveGameId': typeof SaveGameSaveGameIdRoute
  '/mock/': typeof MockIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/newGame': typeof NewGameRoute
  '/game/$gameIri': typeof GameGameIriRoute
  '/mock/$mockName': typeof MockMockNameRoute
  '/saveGame/$saveGameId': typeof SaveGameSaveGameIdRoute
  '/mock': typeof MockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/newGame': typeof NewGameRoute
  '/game/$gameIri': typeof GameGameIriRoute
  '/mock/$mockName': typeof MockMockNameRoute
  '/saveGame/$saveGameId': typeof SaveGameSaveGameIdRoute
  '/mock/': typeof MockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/newGame'
    | '/game/$gameIri'
    | '/mock/$mockName'
    | '/saveGame/$saveGameId'
    | '/mock/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/newGame'
    | '/game/$gameIri'
    | '/mock/$mockName'
    | '/saveGame/$saveGameId'
    | '/mock'
  id:
    | '__root__'
    | '/'
    | '/newGame'
    | '/game/$gameIri'
    | '/mock/$mockName'
    | '/saveGame/$saveGameId'
    | '/mock/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewGameRoute: typeof NewGameRoute
  GameGameIriRoute: typeof GameGameIriRoute
  MockMockNameRoute: typeof MockMockNameRoute
  SaveGameSaveGameIdRoute: typeof SaveGameSaveGameIdRoute
  MockIndexRoute: typeof MockIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/newGame': {
      id: '/newGame'
      path: '/newGame'
      fullPath: '/newGame'
      preLoaderRoute: typeof NewGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/': {
      id: '/mock/'
      path: '/mock'
      fullPath: '/mock/'
      preLoaderRoute: typeof MockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saveGame/$saveGameId': {
      id: '/saveGame/$saveGameId'
      path: '/saveGame/$saveGameId'
      fullPath: '/saveGame/$saveGameId'
      preLoaderRoute: typeof SaveGameSaveGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/$mockName': {
      id: '/mock/$mockName'
      path: '/mock/$mockName'
      fullPath: '/mock/$mockName'
      preLoaderRoute: typeof MockMockNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameIri': {
      id: '/game/$gameIri'
      path: '/game/$gameIri'
      fullPath: '/game/$gameIri'
      preLoaderRoute: typeof GameGameIriRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewGameRoute: NewGameRoute,
  GameGameIriRoute: GameGameIriRoute,
  MockMockNameRoute: MockMockNameRoute,
  SaveGameSaveGameIdRoute: SaveGameSaveGameIdRoute,
  MockIndexRoute: MockIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
