/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NewGameImport } from './routes/newGame'
import { Route as AboutImport } from './routes/about'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as SaveGameSaveGameIdImport } from './routes/saveGame.$saveGameId'
import { Route as MockMockNameImport } from './routes/mock/$mockName'

// Create/Update Routes

const NewGameRoute = NewGameImport.update({
  id: '/newGame',
  path: '/newGame',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SaveGameSaveGameIdRoute = SaveGameSaveGameIdImport.update({
  id: '/saveGame/$saveGameId',
  path: '/saveGame/$saveGameId',
  getParentRoute: () => rootRoute,
} as any)

const MockMockNameRoute = MockMockNameImport.update({
  id: '/mock/$mockName',
  path: '/mock/$mockName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/newGame': {
      id: '/newGame'
      path: '/newGame'
      fullPath: '/newGame'
      preLoaderRoute: typeof NewGameImport
      parentRoute: typeof rootRoute
    }
    '/mock/$mockName': {
      id: '/mock/$mockName'
      path: '/mock/$mockName'
      fullPath: '/mock/$mockName'
      preLoaderRoute: typeof MockMockNameImport
      parentRoute: typeof rootRoute
    }
    '/saveGame/$saveGameId': {
      id: '/saveGame/$saveGameId'
      path: '/saveGame/$saveGameId'
      fullPath: '/saveGame/$saveGameId'
      preLoaderRoute: typeof SaveGameSaveGameIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRoute
  '/about': typeof AboutRoute
  '/newGame': typeof NewGameRoute
  '/mock/$mockName': typeof MockMockNameRoute
  '/saveGame/$saveGameId': typeof SaveGameSaveGameIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRoute
  '/about': typeof AboutRoute
  '/newGame': typeof NewGameRoute
  '/mock/$mockName': typeof MockMockNameRoute
  '/saveGame/$saveGameId': typeof SaveGameSaveGameIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRoute
  '/about': typeof AboutRoute
  '/newGame': typeof NewGameRoute
  '/mock/$mockName': typeof MockMockNameRoute
  '/saveGame/$saveGameId': typeof SaveGameSaveGameIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/newGame'
    | '/mock/$mockName'
    | '/saveGame/$saveGameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/newGame'
    | '/mock/$mockName'
    | '/saveGame/$saveGameId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/about'
    | '/newGame'
    | '/mock/$mockName'
    | '/saveGame/$saveGameId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRoute
  AboutRoute: typeof AboutRoute
  NewGameRoute: typeof NewGameRoute
  MockMockNameRoute: typeof MockMockNameRoute
  SaveGameSaveGameIdRoute: typeof SaveGameSaveGameIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRoute,
  AboutRoute: AboutRoute,
  NewGameRoute: NewGameRoute,
  MockMockNameRoute: MockMockNameRoute,
  SaveGameSaveGameIdRoute: SaveGameSaveGameIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/about",
        "/newGame",
        "/mock/$mockName",
        "/saveGame/$saveGameId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/newGame": {
      "filePath": "newGame.tsx"
    },
    "/mock/$mockName": {
      "filePath": "mock/$mockName.tsx"
    },
    "/saveGame/$saveGameId": {
      "filePath": "saveGame.$saveGameId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
