# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Pages

on:
    # Runs on pushes targeting the default branch
    push:
        branches: [ "main" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:

    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   name: Install pnpm
                uses: pnpm/action-setup@v4
            -   name: Use Node.js 23
                uses: actions/setup-node@v4
                with:
                    node-version: 23
                    cache: 'pnpm'
            -   name: Install dependencies
                run: pnpm install

            -   name: Build project
                run: pnpm run build

            -   name: Upload production-ready build files
                uses: actions/upload-artifact@v3
                with:
                    name: production-files
                    path: ./dist

    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
            -   name: Download artifact
                uses: actions/download-artifact@v4
                with:
                    name: production-files
                    path: ./dist

            -   name: Deploy to GitHub Pages
                uses: peaceiris/actions-gh-pages@v4
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./dist